apiVersion: v1
kind: Service
metadata:
  name: fakes3
  labels:
    name: fakes3
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      targetPort: 8080
      protocol: TCP
  selector:
    name: fakes3
