apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb
  labels:
    name: mariadb
spec:
  replicas: 1
  selector:
    name: mariadb
  template:
    metadata:
      labels:
        name: mariadb
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:10.1.13-r0
          env:
            - name: MARIADB_DATABASE
              value: redmine_production
            - name: MARIADB_USER
              value: redmine
            - name: MARIADB_PASSWORD
              value: secretpassword
          ports:
            - containerPort: 3306
              protocol: TCP
              name: mariadb
          livenessProbe:
            TCPSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
