apiVersion: v1
kind: Service
metadata:
  name: redmine
  labels:
    name: redmine
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 3000
      protocol: TCP
  selector:
    name: redmine
