apiVersion: v1
kind: ReplicationController
metadata:
  name: redmine
  labels:
    name: redmine
spec:
  replicas: 3
  selector:
    name: redmine
  template:
    metadata:
      labels:
        name: redmine
    spec:
      containers:
        - name: redmine
          image: gcr.io/bitnami-tutorials/redmine
          env:
            - name: DATABASE_NAME
              value: redmine_production
            - name: DATABASE_USER
              value: redmine
            - name: DATABASE_PASSWORD
              value: secretpassword
            - name: REDMINE_SESSION_TOKEN
              value: MySecretSessionTokenProtectsMeFromBlackHats
            - name: GOOGLE_STORAGE_ACCESS_KEY_ID
              value: GOOGUF56OWN3R3LFYOZE
            - name: GOOGLE_STORAGE_SECRET_ACCESS_KEY
              value: A+uW0XLz9Y+EHUGRUf1V2uApcI/TenhBtUnPao7i
            - name: GOOGLE_STORAGE_BUCKET
              value: redmine-uploads
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1
