apiVersion: v1
kind: Service
metadata:
  name: wordpress-apache
  labels:
    name: wordpress-apache
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: wordpress-apache
