apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress-apache
  labels:
    name: wordpress-apache
spec:
  replicas: 3
  selector:
    name: wordpress-apache
  template:
    metadata:
      labels:
        name: wordpress-apache
    spec:
      containers:
        - name: wordpress-apache
          image: tutorials/wordpress-apache
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
