apiVersion: v1
kind: Service
metadata:
  name: wordpress-php
  labels:
    name: wordpress-php
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    name: wordpress-php
