apiVersion: v1
kind: Service
metadata:
  name: liferay
  labels:
    name: liferay
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: liferay
