apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb
  labels:
    name: mariadb
spec:
  replicas: 1
  selector:
    name: mariadb
  template:
    metadata:
      labels:
        name: mariadb
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:5.5.45-0-r01
          args:
            - --max_connect_errors=1000
          env:
            - name: MARIADB_USER
              value: myapp
            - name: MARIADB_PASSWORD
              value: secretpassword
            - name: MARIADB_DATABASE
              value: myappdb
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /bitnami/mariadb/data
          livenessProbe:
            TCPSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
      volumes:
        - name: mariadb-persistent-storage
          gcePersistentDisk:
            pdName: mariadb-disk
            fsType: ext4
